const CONNECTION_STATE = {
  CONNECTED: "CONNECTED",
  CONNECTING: "CONNECTING",
  FAILED: "FAILED",
};

const SOCKET_EVENTS = {
  VIDEO_ENABLED: "VIDEO_ENABLED",
  VIDEO_DISABLED: "VIDEO_DISABLED",
  AUDIO_ENABLED: "AUDIO_ENABLED",
  AUDIO_DISABLED: "AUDIO_DISABLED",
  VIDEO_PAUSED: "VIDEO_PAUSED",
  VIDEO_RESUMED: "VIDEO_RESUMED",
  AUDIO_MUTED: "AUDIO_MUTED",
  AUDIO_UNMUTED: "AUDIO_UNMUTED",
};

const CHAT_EVENTS = {
  TYPING: "TYPING",
  CHAT: "CHAT",
  NOT_TYPING: "NOT_TYPING",
};

export { CONNECTION_STATE, SOCKET_EVENTS, CHAT_EVENTS };
